SMTP_USER = "creddtcrntechapplication@gmail.com"
SMTP_PASS = "qpbn elaf xpfh tjqr"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465
DATABASE_URL = "postgresql://postgres:t%21U8eLJ%2CUy%3Ffww6@db.hexwfdslcjwstzzfjxym.supabase.co:5432/postgres"

