# secrets.toml
SMTP_USER = "creddtcrntechapplication@gmail.com"
SMTP_PASS = "qpbnelafxpfhtjqr"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465

DATABASE_URL = "postgresql://postgres.hexwfdslcjwstzzfjxym:t!U8eLJ%2CUy?fww6@aws-1-sa-east-1.pooler.supabase.com:6543/postgres"
