# secrets.toml

BREVO_API_KEY = "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"
BREVO_FROM_EMAIL = "creddtcrntechapplication@gmail.com"
BREVO_FROM_NAME = "CREDDT CRNTECH APPLICATION"

DATABASE_URL = "postgresql://postgres.hexwfdslcjwstzzfjxym:t!U8eLJ%2CUy?fww6@aws-1-sa-east-1.pooler.supabase.com:6543/postgres"
APP_BASE_URL = "https://creddr-crntech.onrender.com"
